#!/bin/bash

# Variables
e=0
option_selected=$1
projects_path="/home/yarso/Escritorio/C#Apps/" # My directory to save it (personal)

# Detect & Show Projects - Function
function show_projects(){
    for project in `ls $projects_path`; do
        if [ -d $projects_path$project/"bin" ]; then
            if [ $e -eq 0 ]; then
                echo -e "\nThere are your projects: \n"
            fi
            echo $project
            (( e+=1 ))
        fi
    done
    if [ $e -eq 0 ]; then
        error "\nERROR. Nothing here, i think you dont have projects"
    fi
}

# Action - Function ?? -note. upgrade to the project_name 
function action(){
    if [ $e -gt 0 ]; then
        echo -e -n "\nProject name: "
        read project_name
        if [[ $1 == "del" ]]; then
            if [ ! -d $projects_path$project_name ]; then 
                error "\nERROR. That's only in your mind"
            else
                sudo rm -r $projects_path$project_name
                success "\nSUCCESS. Operation finished"
            fi
        elif [[ $1 == "op" ]]; then
            if [ ! -d $projects_path$project_name ]; then 
                error "\nERROR. That's only in your mind"
            else
                code $projects_path$project_name
                success "\nSUCCESS. Operation finished"
            fi
        fi
    else
        # This isnt possible, but we will let them right here
        echo $project_name
        error "\nERROR. Nothing here, i think you dont have projects"
    fi
}

# Error - Function
function error(){
    echo -e $1
    
    exit 1

}

# Success - Function
function success(){
    echo -e $1

    exit 0 

}


if [ $# -lt 1 ]; then
    error "\nERROR. Arguments are missing (-crP, -delP, -oP)(P = project)"
fi

if [[ $option_selected != "-crP" && $option_selected != "-delP" && $option_selected != "-oP" ]]; then
    error "\nCongrats, you are retarded. Bay bay"
fi

# Create Project
if [[ $option_selected == "-crP" ]]; then
    echo -n "New project name: "
    read project_name
    if [ -d $projects_path$project_name ]; then
        error "\nERROR. Directory already exist"
    else
        mkdir $projects_path$project_name
        cd $projects_path$project_name && dotnet new console
        code $projects_path$project_name
        success "\nSUCCESS. Operation finished"
    fi
        
# Delete Project
elif [[ $option_selected == "-delP" ]]; then
    show_projects 
    action "del"

# Open Project
elif [[ $option_selected == "-oP" ]]; then
    show_projects
    action "op"
fi
