#!/bin/bash

# Variables
e=0
option_selected=$1
projects_path="/opt/lampp/htdocs/" # Default directory to save it (XAMPP)

# Error - Function
function error(){
    echo -e $1
    
    exit 1

}

# Success - Function
function success(){
    echo -e $1

    exit 0 

}

# Action - Function
function action(){
    if [ $e -gt 0 ]; then   
        echo -e -n "\nProject project_name: "
        read project_name
        if [[ $1 == "del" ]]; then
            if [ ! -d $projects_path$project_name ]; then 
                error "\nERROR. That's only in your mind"
            else
                sudo rm -r $projects_path$project_name
                success "\nSUCCESS. Operation finished"
            fi
        elif [[ $1 == "op" ]]; then
            if [ ! -d $projects_path$project_name ]; then 
                error "\nERROR. That's only in your mind"
            else
                code $projects_path$project_name
                success "\nSUCCESS. Operation finished"
            fi
        fi
    else
        # This isnt possible, but we will let them right here
        error "\nERROR. Nothing here, i think you dont have projects"
    fi
}

# Show projects - Function
function show_projects(){
    for project in `ls $projects_path`; do
        if [ -f $projects_path$project/"init_file.txt" ]; then
            if [ $e -eq 0 ]; then
                echo -e "\nThere are your projects: \n"
            fi
            echo $project
            (( e+=1 ))
        fi
    done
    if [ $e -eq 0 ]; then
        error "\nERROR. Nothing here, i think you dont have projects"
    fi
}

# Strcture Control Main
if [ $# -lt 1 ]; then
    error "\nERROR. Arguments are missing (-on, -off, -r, -crP, -delP, -oP)(P = project)"
fi

if [[ $option_selected != "-on" && $option_selected != "-off" && $option_selected != "-r" && $option_selected != "-crP" && $option_selected != "-delP" && $option_selected != "-oP" ]]; then
    error "\nCongrats, you are retarded. Bay bay"
fi

# Start XAMPP
if [[ $option_selected == "-on" ]]; then
    sudo xampp startapache
    sudo xampp startmysql

    exit 0

# Stop XAMPP
elif [[ $option_selected == "-off" ]]; then
    sudo xampp stopapache
    sudo xampp stopmysql

exit 0

# Reload XAMPP
elif [[ $option_selected == "-r" ]]; then
    sudo xampp reloadapache
    sudo xampp reloadmysql

    exit 0

# Create Project
elif [[ $option_selected == "-crP" ]]; then
    echo -n "New project project_name: "
    read project_name
    if [ -d $projects_path$project_name ]; then
        error "\nERROR. Directory already exist"
    fi
    sudo mkdir $projects_path$project_name
    sudo chown -R $USER:$users $projects_path$project_name
    echo "This text file only help script to identify this directory as a php project" >> $projects_path$project_name/init_file.txt
    code $projects_path$project_name
    success "\nSUCCESS. Operation finished"
        
# Delete Project
elif [[ $option_selected == "-delP" ]]; then
    show_projects
    action "del"

# Open Project
elif [[ $option_selected == "-oP" ]]; then
    show_projects
    action "op"
fi 
