#!/bin/bash

# Variables
e=0
option=$1
pr="/opt/lampp/htdocs/" # Default directory to save it (XAMPP)

# Error - Function
function error(){
    echo -e $1
    
    exit 1

}

# Success - Function
function success(){
    echo -e $1

    exit 0 

}

# Action - Function
function action(){
    if [ $e -gt 0 ]; then   
        echo -e -n "\nProject name: "
        read name
        if [[ $1 == "del" ]]; then
            if [ ! -d $pr$name ]; then 
                error "\nERROR. That's only in your mind"
            else
                sudo rm -r $pr$name
                success "\nSUCCESS. Operation finished"
            fi
        elif [[ $1 == "op" ]]; then
            if [ ! -d $pr$name ]; then 
                error "\nERROR. That's only in your mind"
            else
                code $pr$name
                success "\nSUCCESS. Operation finished"
            fi
        fi
    else
        # This isnt possible, but we will let them right here
        error "\nERROR. Nothing here, i think you dont have projects"
    fi
}

# Show projects - Function
function show_projects(){
    for p in `ls $pr`; do
        if [ -f $pr$p/"init_file.txt" ]; then
            if [ $e -eq 0 ]; then
                echo -e "\nThere are your projects: \n"
            fi
            echo $p
            (( e+=1 ))
        fi
    done
    if [ $e -eq 0 ]; then
        error "\nERROR. Nothing here, i think you dont have projects"
    fi
}

# Strcture Control Main
if [ $# -lt 1 ]; then
    error "\nERROR. Arguments are missing (-on, -off, -r, -crP, -delP, -oP)(P = project)"
fi

if [[ $option != "-on" && $option != "-off" && $option != "-r" && $option != "-crP" && $option != "-delP" && $option != "-oP" ]]; then
    error "\nCongrats, you are retarded. Bay bay"
fi

# Start XAMPP
if [[ $option == "-on" ]]; then
    sudo xampp startapache
    sudo xampp startmysql

    exit 0

# Stop XAMPP
elif [[ $option == "-off" ]]; then
    sudo xampp stopapache
    sudo xampp stopmysql

exit 0

# Reload XAMPP
elif [[ $option == "-r" ]]; then
    sudo xampp reloadapache
    sudo xampp reloadmysql

    exit 0

# Create Project
elif [[ $option == "-crP" ]]; then
    echo -n "New project name: "
    read name
    if [ -d $pr$name ]; then
        error "\nERROR. Directory already exist"
    fi
    sudo mkdir $pr$name
    sudo chown -R $USER:$users $pr$name
    echo "This text file only help script to identify this directory as a php project" >> $pr$name/init_file.txt
    code $pr$name
    success "\nSUCCESS. Operation finished"
        
# Delete Project
elif [[ $option == "-delP" ]]; then
    show_projects
    action "del"

# Open Project
elif [[ $option == "-oP" ]]; then
    show_projects
    action "op"
fi 
